### ISSUE TITLE
its just blinking random colors for me 

### ISSUE THREAD

**Issue by bwwq** [fusionhuh/wava#2]
https://user-images.githubusercontent.com/82705391/185027469-5d46f276-ee4f-4490-a4ac-1e151ec7f9e5.mp4

**Comment by fusionhuh** [comment]
hi there,

first of all, i noticed that the window is too large for the terminal, which is causing the erratic movement in the video. you can adjust its size with the arrow keys. ill probably update the default size because this appears to be a recurring issue.

secondly, the color response in wava works by calculating the most dominant note present in the audio and assigning a color to it from the selected color palette (which is currently "pride" as you can see under the window). as the note being played changes in your music, wava is changing the color it outputs, so it is actually working as intended here. if you don't like the color variance, you can try using one of the more monochromatic palettes available like neptune or mercury. you can change the palette with `z` and `x`. 

i also noticed that some of the lower notes aren't being picked up, you could try lowering the noise gate with `c` to see if that helps.

to add shapes as shown in the reddit post, use number keys `1` `2` and `3`. reading the usage section will help you customize further :+1: 

let me know if those suggestions were unsatisfactory, i could add different modes to  make the background less dependent on pitch
